import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextAuth With Mongodb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Toaster position="top-left" reverseOrder={false} />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
